### ISSUE TITLE
AppVeyor support

### ISSUE THREAD

**Issue by JakeGinnivan** [fixie/fixie#104]
I have been reading the various threads on this and just wanted to continue the discussion.

It seems the plan is to remove specific build servers from the console application and split into separate exes. So we would have TeamCity.Console.exe and AppVeyor.Console.exe and such? Any idea when the teamcity listener will be pulled out into it's own repo so the pattern can be followed for others?

**Comment by plioi** [comment]
Despite those earlier conversations, the main Fixie.Console.exe has legitimate support for AppVeyor built-in now. Available in 1.0.0.39 https://github.com/fixie/fixie/releases/tag/v1.0.0.39
