### ISSUE TITLE
mutually exclusive build methods

### ISSUE THREAD

**Issue by VioletTape** [fixie/fixie#105]
Hello! 
I've discovered that methods: 
* ```NameEndsWith() ```
* ```Where() ```

operates as mutually exclusive (or ```Where()``` has higher coeff of usage), that is weird because of nature of the Classes' methods that act as a Builder. 

```csharp
public class Car {  
}

public class CarTests{
  public void CarShould(){
  }
}

public class WhenCarMoving {
    public void FuelShouldConsumed() {
    }

    public void DriverShouldPresent() {
     }

    public void HornMayBeUsed() {
    }
}


public class CustomConvention   : Convention {
    public CustomConvention  () {
        Classes
            .InTheSameNamespaceAs(typeof(CustomConvention ))
            .NameEndsWith("Tests") // if not commented I got only one test from the CarTests class
            .Where(c => c.Name.StartsWith("When") || c.Name.EndsWith("Tests"));

        Methods
            .Where(method => method.IsVoid());
    }
}
```

I think that it's contrintuitive that ```NameEndsWith()``` not applied to ```Where()``` with logical "or" operator.

**Comment by VioletTape** [comment]
My bad, didn't catch from documentation that any additional matching clauses will be applied by AND to the predefined one.

**Comment by plioi** [comment]
Right.  All of the conditions must be true for the class to be considered a test class.  For an "or" decision, that has to be explicit with an || inside the condition.

Note that InTheSameNamespaceAs and .NameEndsWith(...) both work by calling Where(...).  They're just shorthand for common situations: https://github.com/fixie/fixie/blob/9d080b64fce62ced7a09b912dcdb0be1288a1173/src/Fixie/Conventions/ClassExpression.cs

A candidate class is a match if all the conditions are met: https://github.com/fixie/fixie/blob/9d080b64fce62ced7a09b912dcdb0be1288a1173/src/Fixie/Internal/ClassDiscoverer.cs#L32
