### ISSUE TITLE
NUnit Report problem.

### ISSUE THREAD

**Issue by rupreck** [fixie/fixie#117]
Hello - We are getting a problem when importing the NUnit report into our SQA product. The  message received is:

[3] - ERROR: Caused by: Missing attribute "errors" in element <test-results> in report-tests.xml at line 2

Looking back through the various nunit schemas this is a required attribute in version 2.6 (Feb 2012 onwards) .

See: http://www.nunit.org/docs/2.6/files/Results.xsd 

Is there a solution?

**Comment by plioi** [comment]
This fix has been released in 1.0.0.29.  If you encounter further XML issues, please create a new issue.

**Comment by rupreck** [comment]
Many thanks.  Will test it today.
