### ISSUE TITLE
Creation of parameters after fixture wrapper execution

### ISSUE THREAD

**Issue by carl-berg** [fixie/fixie#125]
Hi,

I've been wrestling a bit with Fixie trying to get it to do what i want it to do. 

I am currently running some integration tests and would like to create some instances during startup once for the entire test project (an NHibernate session factory for instance) and then during parameter loading for each test method, be able to use those entities but it seems that parameter loading happens before the Fixture Execution wrapping. Is there any way to accomplish this or is there a better way to do this?

**Comment by plioi** [comment]
You're right that parameter resolution is happening far too early in the pipeline.  It's part of what Pedro is bumping into here in #96.  It definitely needs to change.  I'll take a closer look in the next 48 hours, to decide whether it can safely be treated as a bug fix against 1.x or whether it has to be treated as a breaking change for 2.x.

**Comment by carl-berg** [comment]
Nice. If it's something i can help out with (without having an intimate knowledge of the codebase) I'd be glad to help out (test cases or whatever).

**Comment by plioi** [comment]
5 and a half years later, Fixie 3's API addresses the fundamental flaws in this old design. Closing this due to age and the fact that the version 3 API should give everyone sufficient control over parameterization now.
