### ISSUE TITLE
Typo in Visual Studio Runner web page

### ISSUE THREAD

**Issue by BrainCrumbz** [fixie/fixie#135]
There's a repeated typo in [Visual Studio Runner web page](http://fixie.github.io/docs/visual-studio-runner/). At least a couple of times it says `Exporer` instead of `Explorer`.

Didn't know where to notify web site issues, so we opted for Github repo. HTH

**Comment by plioi** [comment]
Fixed, thank you.  For future reference, the content of the documentation site is in the following repo: https://github.com/fixie/fixie.github.io

**Comment by BrainCrumbz** [comment]
Thanks for info. By any chance, is that link already mentioned on documentation site? I've seen other projects doing that and it seems useful for flagging things like this.

**Comment by plioi** [comment]
It's not yet, but that's a good suggestion.

**Comment by BrainCrumbz** [comment]
This is one (very good) example I remembered: 

http://omniscientjs.github.io/api/01-omniscient-api-reference/

![omniscient api reference - waterfox](https://cloud.githubusercontent.com/assets/3185573/12023383/36cf1822-ad99-11e5-92af-4b6d5e962081.png)

**Comment by plioi** [comment]
@BrainCrumbz  A simple change to the documentation pages' layout has enabled this feature.  Documentation pages now have an "edit this page" link similar to the one you referenced.  Thanks a lot for the suggestion!

**Comment by BrainCrumbz** [comment]
Cool!
