### ISSUE TITLE
Fixie Not Exiting

### ISSUE THREAD

**Issue by rupreck** [fixie/fixie#142]
## Steps to Reproduce
Running Fixie via OpenCover does not exit on some test library projects. The task manager continues to show it is active hours after it should have completed tests (within a few minutes).  Is there a reason this might happen? Is there a way to tell it to close from the command line at the end of a test run eg. timeout. This does not happen with all projects using Fixie.

Looking at the code it appears the test library creates an IOCConvention derived from Convention then registers assemblies using Autofac ContainerBuilder and creates the container. It then calls ClassExecution and calls CreateInstancePerClass to run test cases.

## Expected Behavior
Fixie should exit when tests are completed, or it should support a timeout (with errorcode) so that dependent processes such as opencover can complete their required handling.

## Actual Behavior
Fixie remains active, cpu time continues to tick over.

**Comment by plioi** [comment]
Honestly, this seems to be a recurring issue with OpenCover across all test frameworks.

See similar reports for xUnit https://github.com/OpenCover/opencover/issues/110#issuecomment-7162259 and NUnit https://github.com/OpenCover/opencover/issues/94

**Comment by rupreck** [comment]
When the OpenCover default filter +[*]* is in place it fails.  However when explicitly set to the name of the library eg. +[project.lib]* it completes fine.  Thanks for the help, it is fixed now.
