### ISSUE TITLE
Support .NET Core "Preview" Tooling

### ISSUE THREAD

**Issue by plioi** [fixie/fixie#145]
As described in the [Project Roadmap](https://github.com/fixie/fixie/wiki), Fixie 2.x should leverage .NET Core, and it should allow testing of projects that leverage .NET Core.  This Issue is meant to track the high-level to-do list and as a starting point for discussion of the implementation.

*Note: This issue was originally intended to cover full .NET Core support. In late 2016, Microsoft introduced significant breaking changes to their .NET Core testing infrastructure while also introducing a VS2017 prerequisite. This issue has since changed in name and scope to represent only the work in support of the "Preview" tooling in place during the summer and fall of 2016. In other words, this issue covers the work involved in support of the project.json / xproj style of projects, before `dotnet test` was rewritten to work atop MSBuild.*

- [x] Revise internal messaging infrastructure to lessen dependencies on AppDomains.
- [x] Console runner runs exactly one test assembly per run (to meet the _dotnet test_ model).
- [x] Revise XML reporting command line arguments and file save paths (to account for the _dotnet test_ model).
- [x] Port a representative library (Parsley) to .NET Core RC2 (using xUnit temporarily).
- [x] Convert all projects to .NET Core RTM project files, while still targeting only the regular .NET Framework.
- [x] Update Parsley to .NET Core RTM.
- [x] Migrate the existing console runner to become the _dotnet test_ runner's console mode implemetnation.
- [x] Extend the _dotnet test_ runner to support IDE mode.
- [x] Refactor the existing legacy Visual Studio runner to defer to dotnet-test-fixie.exe in IDE mode.
- [x] Publish a prerelease NuGet package of 2.x for initial round of feedback.
- [x] Consolidate all remaining AppDomain dependencies to within the _dotnet test_ runner.
- [x] Cross-compile Fixie.dll
- [x] Cross-compile Fixie.Execution.dll
- [x] Cross-compile Fixie.TestDriven
- [x] Cross-compile dotnet-test-fixie.exe
- [x] Enable dotnet-test-fixie to be located by dotnet-test when not targeting the full .NET Framework.
- [x] Cross-compile Fixie.Samples
- [x] Cross-compile Fixie.Tests
- [x] Fixie.Tests and Fixie.Samples pass for full framework as well as netcoreapp/netstandard.

**Comment by mderriey** [comment]
Hi,
I'd like to help with both porting fixie to .NET Core.
Would you accept contributions?

**Comment by Martin-Bohring** [comment]
@plioi 
I am just getting into .Net Core, so forgive me my ignorance.

> Drop the plain console runner in favor of dotnet test?
> Drop the legacy Visual Studio runner in favor of dotnet test?

Can test still be executed interactively from VS after these moves?

**Comment by mderriey** [comment]
Yes they would, the [.NET Core test protocol](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/test-protocol) has design-time capabilities that would allow fixie to integrate nicely with Visual Studio, both for listing and executing tests.

**Comment by Martin-Bohring** [comment]
Ah, thanks good to know,
I really need to catch up on .Net Core :smile:

**Comment by plioi** [comment]
@mderriey I just converted the project files over to the new project.json formats in #146. It would still only work for the regular .NET Framework, and would not yet support "dotnet test".  As soon as I publish a prerelease NuGet package, sometime next week, I'd appreciate some help testing that I haven't broken everything in the process.

**Comment by dennisroche** [comment]
Anybody working on the `Add a dotnet test runner` item?

**Comment by plioi** [comment]
@dennisroche Yes, I'm claiming that one. Between NUnit's solution, xUnit's solution, and Fixie's existing older-style Visual Studio plugin, I should have enough to go on.

**Comment by dennisroche** [comment]
@plioi need help with anything else? :)

**Comment by plioi** [comment]
# 2.0.0-alpha-0001

2.0.0-alpha-0000 was a dumpster fire, so let's never speak of it again. Announcing [2.0.0-alpha-0001](https://www.nuget.org/packages/Fixie/2.0.0-alpha-0001)! This release has been published for early adopters to experiment with.

*What it IS NOT:* This release will not test cross-platform projects, such as projects that target netstandard.

*What it IS:* Integration with the new dotnet tooling, both at the command line and in the Visual Studio Test Explorer, **for old csproj test projects, and for new xproj/project.json test projects which target the normal framework: net45 and up.** Much progress has been made to support netstandard too, but it's just not there yet.

## Known Issues:
1. Attempting to run this against a 32 bit test assembly will not work. If you use Test Explorer, be sure it is set to 64 bit mode.
2. When using Test Explorer against an xproj/project.json project, expect the Output \ Tests pane to include some misleading output in which it claims to skip a test assembly "because it is not a test assembly", along with more output demonstrating that they are in fact being executed. Visual Studio is mistakenly running BOTH a legacy csproj style runner, which accomplishes no work, as well as the dotnet test variety which does provide results.

## Working Examples
1. Rook is an old csproj style project, which demonstrates that the 2.x series can still work for such projects. Instead of using the new dotnet tooling, the build script invokes dotnet-test-fixie.exe directly. View the source as of this commit: https://github.com/plioi/rook/tree/1254f718596dea83d2aee4579fa81f8872390444
2. Fixie.Runners.Sandbox is a sample project used in integration testing Fixie.  Here we see new style xproj/project.json projects, *but note that at this point they still have to target the regular framework, net45*. The build script uses the new dotnet tooling, and Test Explorer also works via the new dotnet tooling. View the source as of this commit: https://github.com/fixie/fixie.runners.sandbox/tree/9c08a95186d5fc76b538a224590adb56e5a308d3

## Your Project.json

A typical test project's project.json will look like this:

```json
{
  "testRunner": "fixie",
  "dependencies": {
    "Some.Project.In.Your.Solution": { "target": "project" },
    "Fixie": "2.0.0-alpha-0001",
    "Should": "1.1.20"
  },
  "frameworks": {
    "net45": {}
  }
}
```

**Comment by plioi** [comment]
Because Microsoft has introduced significant breaking changes to .NET Core testing infrastructure while also introducing a new VS2017 prerequisite, I have renamed this issue to reflect what it really is, and am closing it. The project.json / xproj tooling is to be replaced soon by Microsoft, and a separate issue will cover integration with that tooling once the dust settles.  2.0.0-alpha-0001 remains for those currently on the deprecated project.json / xproj tooling, but we can't sink more time and effort into improving that integration when it's disappearing anyway.

**Comment by alexidsa** [comment]
Is there a way to use fixie as part of netcoreapp1.1 project?
