### ISSUE TITLE
Does Fixie Work with Visual Studio 2015's Create Unit Tests Dialog?

### ISSUE THREAD

**Issue by vector-man** [fixie/fixie#153]
Does Fixie work with the Create Unit Tests dialog, shown here?: https://i-msdn.sec.s-msft.com/en-us/library/hh694602.4e58cef6-eda4-48b9-9ff3-d64c1ad3247a(v=vs.140).jpeg?f=255&MSPPError=-2147217396

**Comment by plioi** [comment]
I've never seen that dialog. Are you referring to this, which was removed from Visual Studio? http://stackoverflow.com/questions/9547055/where-is-the-create-unit-tests-selection

**Comment by vector-man** [comment]
It's in VS 2015. Here is more information: https://www.visualstudio.com/en-us/docs/test/developer-testing/getting-started/create-unit-tests-menu

**Comment by plioi** [comment]
From the documentation, "At present only C# with MSTest and Xunit test frameworks are supported, but will be extended to other langauges and frameworks in the future." For this feature to be supported, it seems Visual Studio itself would need to be updated to recognize Fixie in order for the dialog to have meaning, and even at that I don't think it would be feasible.  One Fixie user may go with the default convention, in which there's so little boilerplate that the dialog wouldn't save the user much time; the next Fixie user might define a custom attribute or naming convention of their own to identify tests, rendering the dialog's output wrong.
