### ISSUE TITLE
Support .NET Core / VS2017 RTM Tooling

### ISSUE THREAD

**Issue by plioi** [fixie/fixie#155]
Microsoft has released VS2017 with its associated msbuild-based `dotnet` tool implementation.

Fixie 2.0.0-alpha-0001 was a worthwhile experiment for the now-deprecated project.json / xproj tooling, but maintaining that branch is no longer our goal. All of the ideas from that branch that are relevant to the VS2017 tooling have already been included in the `develop` branch, our main line of development.

This is a parent issue for the effort to work with the VS2017 tooling.  If an issue is marked `Up for Grabs`, please claim it by joining the discussion on that issue.  If an issue is marked `In Progress`, it has been claimed, but please join in the discussion to help out!

- [x] Remove `<DebugType>full</DebugType>` from Fixie.Tests.csproj (No longer applicable)
- [x] Integrate with `dotnet test` #167
- [x] Build packages without a `nupsec` file #168 (No longer applicable)
- [x] Implement `dotnet fixie` to replace the console runners
- [x] Target netstandard

**Comment by giggio** [comment]
How is this progressing? Any timeline, yet?

**Comment by plioi** [comment]
Prerelease version 2.0.0-alpha-0002 is ready for early adopters to experiment with.

See https://github.com/fixie/fixie.integration for a working example of a solution which depends on the new tooling.

VS2017 Update 3 and above are officially supported, and only for the modern compact csproj format.  It would be useful to get information on whether there are issues on VS2015 and the older verbose csproj format in case it's easy to improve that scenario, but we may have to use 2017 as a cutoff for 2.x, since so much of the surrounding ecosystem has changed.

Known issues:

* TestDriven.NET integration only works for test assemblies targeting the full .NET Framework. .NET Core support depends on TestDriven.NET itself adopting .NET Core.
* Test Explorer will have no source code line number information available for projects targeting .NET Core. You will not be able to double-click an item in Test Explorer to navigate to the code for that test, and you will not be able to get right-click context menu items on test methods to run those tests. You'll have to view and run tests only through Test Explorer.

To install the Fixie library, add the following package to your test assembly:
`dotnet add package Fixie --version 2.0.0-alpha-0002`

To install the `dotnet fixie` command, add the following package to your test assembly:
`dotnet add package Fixie.Console --version 2.0.0-alpha-0002`

From within a test project folder,
`dotnet fixie --configuration $configuration --no-build`

**Comment by plioi** [comment]
Closing this issue. We'll track further work on .NET Core support in separate issues.

**Comment by giggio** [comment]
What issue is tracking .NET Core support? I couldn't find it? I saw there are alpha of 2.0 in Nuget, but I can't find the issue tracking .NET Standard support?

**Comment by plioi** [comment]
This closed ticket covered the work that got us *to* the current alpha.

#166 is the main up-for-grabs obstacle that needs to be addressed for a final 2.x release.

I have a handful of nice-to-have things in motion such as phasing out the last remaining usages of AppDomain, but there isn't an Issue tracking that.

**Comment by giggio** [comment]
Awesome! I sent a PR to try and fix #166. Let's hope that after that you can release a beta? I want to use it! :)
