### ISSUE TITLE
Tests not discovered in VS2015 Update 3

### ISSUE THREAD

**Issue by seesharper** [fixie/fixie#156]
## Steps to Reproduce
- Create a new class library (4.6.1)
- Create a class named SampleTests
- Create a test method
- Build all
## Expected Behavior
Test being discovered and appearing in the test explorer 

## Actual Behavior
Nothing happends

**Comment by plioi** [comment]
Thanks for reporting this. I have a few questions to help reproduce the issue:

1. Is your test project a *.csproj or a project.json/xproj?
2. Is there any output in the Output pane when you select Tests from the dropdown?
3. Is the Test Explorer set to 32 bit mode or 64 bit mode? Does that match your project's own bitness?
4. What build of Fixie are you running? Does the behavior correct itself if you go backwards to an earlier build?

**Comment by plioi** [comment]
Also, whether the project is old / csproj or not, do you have the .NET Core preview tools installed in VS? They made some changes to the way that works which might be a part of this.

**Comment by seesharper** [comment]
My bad. I was installing the latest pre-release 2.0.0. Switching back to latest stable release solved the issue. 
Keep up the good work. BTW I totally understand that you don't yet have a .Net Core version. Talk about a moving target :)

**Comment by plioi** [comment]
Thanks, that's good to know.

The prerelease is highly experimental, especially with some recent breaking changes by MS.  The 2.0 alpha 0001 build has Test Explorer support, but only for project.json projects.

I'd expect Test Explorer to work as usual for any 1.x build, and any normal csproj.
