### ISSUE TITLE
JIT Annoyance

### ISSUE THREAD

**Issue by rupreck** [fixie/fixie#157]
Running Fixie on a machine with VS installed constantly pulls up the JIT debugger.  This is annoying when run as a service account on a build machine as it appears to the logged in user repeatedly.  Can unhandled exceptions be trapped and logged? e.g. 

[https://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception(v=vs.110).aspx](https://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception(v=vs.110).aspx)

eg.

        /// <summary>
        /// Handles the unhandled exceptions.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="args">The <see cref="System.UnhandledExceptionEventArgs"/> instance containing the event data.</param>
        static void UnhandledExceptionHandler(Object sender, UnhandledExceptionEventArgs args)
        {
            // Get exception
            Exception ex = (Exception)args.ExceptionObject;

            // Log it
            EventLog eventLog = new EventLog();
            eventLog.WriteEntry("Fixie unhandled exception: " + ex.Message + " " + ex.InnerException.Message, EventLogEntryType.Error);
        }

![capture](https://cloud.githubusercontent.com/assets/3411358/21520570/34aa9958-cced-11e6-8a11-73135c0d1706.PNG)

**Comment by plioi** [comment]
Closing for age. I've never reproduced this issue. If there are steps to reproduce, please reopen with details.
