### ISSUE TITLE
Default convention documentation is off

### ISSUE THREAD

**Issue by alexidsa** [fixie/fixie#162]
It seems like default convention documentation is incorrect. It says:

> a test class is any concrete class in your test assembly whose name ends with “Tests”

But instead fixie seems to take any class by default. I have a DeleteData fixture behaviour and fixie is trying to execute its Execute method if I don't specify custom ClassNames as part of convention.

**Comment by plioi** [comment]
http://fixie.github.io/docs/custom-conventions/ could be more explicit about this, but as soon as you have a convention class of your own, the default convention is not used at all, and your convention is free to "start from scratch".

You either want to inherit from DefaultConvention, or you want to imitate DefaultConvention with whatever tweaks you're interested in.  For reference, the DefaultConvention is defined like so:

```cs
namespace Fixie.Conventions
{
    /// <summary>
    /// The default convention is applied to a test assembly whenever the test assembly specifies no custom convention to use.
    ///
    /// <para>A class is a test class if its name ends with "Tests".</para>
    ///
    /// <para>A public instance method in a test class is a test method if it is declared void or async.</para>
    /// </summary>
    public class DefaultConvention : Convention
    {
        public DefaultConvention()
        {
            Classes
                .NameEndsWith("Tests");

            Methods
                .Where(method => method.IsVoid() || method.IsAsync());
        }
    }
```

**Comment by alexidsa** [comment]
DefaultConvention makes total sense. Thanks!

**Comment by plioi** [comment]
Great, let me know if you run into other obstacles.

**Comment by alexidsa** [comment]
By the way, used it in Jimmy's repository: https://github.com/jbogard/ContosoUniversityCore/pull/7
