### ISSUE TITLE
Test's name contains namespace in VS Test Explorer

### ISSUE THREAD

**Issue by Ma3yTa** [fixie/fixie#163]
## Steps to Reproduce
Open Test Explorer in VS 2015

## Expected Behavior
Only test's method name without namespace

## Actual Behavior
Test name contains namespace

**Comment by plioi** [comment]
What would be the expected behavior when 2 test methods have the same name?

**Comment by Ma3yTa** [comment]
Class1.TestMethod1
Class2.TestMethod1

namespace1.Class1.TestMethod1
namespace2.Class1.TestMethod1

**Comment by Ma3yTa** [comment]
Sample how It can be done https://github.com/fixie/fixie/pull/164
