### ISSUE TITLE
Upgrade Mono.Cecil Dependency

### ISSUE THREAD

**Issue by plioi** [fixie/fixie#166]
Visual Studio Test Explorer integration benefits from our ability to tell VS the starting line numbers of each discovered test method. If a test framework provides line number information, then the right-click context menu for running tests in Test Explorer becomes enabled, and users can navigate from Test Explorer to the test method.

We have used the Mono.Cecil NuGet package to accomplish this.  We use Mono.Cecil to read through PDBs in order to calculate the line number of a test method.  Every so often, Microsoft changes the PDB format, and we have to upgrade Mono.Cecil to work with new PDB files.  With VS2017 and .NET Core, the PDB formats changed in a few ways, and Mono.Cecil's latest prerelease apparently supports them.

Unfortunately, this Mono.Cecil upgrade includes a few breaking changes that affect us, so it is a nontrivial upgrade.  We attempted to upgrade in branch `upgrade-mono-cecil` a while back, but that attempt ran into some issue with attempting to access a file that was in use by 'another process'.

We need someone to attempt again, using the latest Mono.Cecil (include prereleases in your version selection).  **Branch off of `develop` and submit your PR back to `develop`.  This will require that you work with VS2017.**

See http://cecil.pe/ (the Mono.Cecil development blog).  See especially the post http://cecil.pe/post/149243207656/mono-cecil-010-beta-1 which describes their breaking API changes, as these directly affect us.

See the current implementation in the `develop` branch:

* https://github.com/fixie/fixie/blob/develop/src/Fixie.VisualStudio.TestAdapter/SourceLocationProvider.cs The class which uses Mono.Cecil to determine line numbers.
* https://github.com/fixie/fixie/blob/develop/src/Fixie.Tests/VisualStudio/TestAdapter/SourceLocationProviderTests.cs Tests of that class - expect to change little if anything here!
* https://github.com/fixie/fixie/blob/develop/src/Fixie.Tests/VisualStudio/TestAdapter/SourceLocationSamples.cs The sample code file used by the tests, illustrating several edge cases. Change this with extreme caution!

**Comment by giggio** [comment]
I think I got it to work. I will send a PR.

**Comment by plioi** [comment]
Closing this as fixed by @giggio in #171.
