### ISSUE TITLE
Integrate with `dotnet test`

### ISSUE THREAD

**Issue by plioi** [fixie/fixie#167]
The VS2017 tooling allows test frameworks to integrate with `dotnet test` as a side effect of integrating with Test Explorer.  Fixie already has a Test Explorer integration for previous versions of Visual Studio.

This likely involves upgrading our existing Test Explorer integration to work against their new integration points.  Looking at xUnit, we likely need to start using the new [Microsoft.TestPlatform.ObjectModel](https://www.nuget.org/packages/Microsoft.TestPlatform.ObjectModel) package as a starting point.

**Comment by plioi** [comment]
Progress update: at this time the 'develop' branch can successfully run `dotnet test` against fixie's own test assemblies.  For some of these runs, the test adapter path has to be specified explicitly, since we're not consuming Fixie as a nuget package here. Consumers of the nuget package don't yet benefit from `dotnet test` since the adapter wouldn't be found at runtime.

**Comment by plioi** [comment]
Close as no longer applicable. Although `dotnet test` works on the latest alpha, we in fact recommend `dotnet fixie` instead, using the Fixie.Console NuGet package.

**Comment by giggio** [comment]
I believe you should support `dotnet test`. It is the standard way to do it. People coming from other test frameworks expect it to be available.

**Comment by plioi** [comment]
Unfortunately, `dotnet test` is not the standard it was meant to be. It was really only made with MSTest in mind. The xUnit team has also abandoned it as a good idea that never really came to fruition. It doesn't even show up in the xUnit documentation anymore, now that `dotnet xunit` works so much better for them.

When used against a netcoreapp test project, with the latest beta release of Fixie, `dotnet test` works. Against a regular .NET Framework test assembly, it'll fail because `dotnet test` makes the mistaken assumption that the test adapter will be found in the same folder as the test assembly. This is a *different* lookup mechanism than the one Test Explorer *successfully* uses, where it considers the Fixie NuGet package contents to properly find the right test adapter. Both Test Explorer and `dotnet test` work by running the Test Explorer plugin, but have this surprising discrepancy in how they decide how to run the right adapter.

I consider that discrepancy to be a bug in `dotnet test`. If they fix it, then `dotnet test` will start working 100% with Fixie, but I'll still recommend that people not use it at all. It's output is hard to read, it incorrectly displays "skipped" test messages with red error coloring, it's slower, and has no useful support for Fixie's command line arguments.
