### ISSUE TITLE
.NET Standard 2.0 Support

### ISSUE THREAD

**Issue by phillipsj** [fixie/fixie#175]
I know this has been mentioned in the past and that you were waiting on .NET Standard 2.0.  Is this something that you are ready to do?  I am willing to help get this going.

Thanks,

**Comment by phillipsj** [comment]
Awesome, I am willing to help in anyway I can.  I will pull down the alpha
and check it out.

**Comment by seesharper** [comment]
@plioi Do you need any help to get this out the door for .Net Core?

**Comment by plioi** [comment]
@seesharper I've been making a lot of improvements in the 2.x "develop" branch as a final push for a beta release.  I'm targeting a beta release by end of March 3, at which point the most useful help will be to pull it down, try it out, and report bugs as separate Issues.

**Comment by plioi** [comment]
https://github.com/fixie/fixie/releases/tag/v2.0.0-beta-0001 is ready for adventurous .NET Core users. :tada:
