### ISSUE TITLE
Parameterized Test Classes

### ISSUE THREAD

**Issue by roend83** [fixie/fixie#177]
Is there a way for me to configure Fixie to execute a test class multiple times only varying the parameters that get passed into the constructor?  I see that I can use ClassExecution.UsingFactory to build the instance with custom parameters, but I would like to be able to vary those parameters and generate multiple instance per class test cases.

**Comment by plioi** [comment]
This is an interesting idea, but is not currently supported.

I'd like to hear more about the concrete use case you have in mind. It would inform some tough questions like "How do we know how many times should the test class be constructed?"

**Comment by roend83** [comment]
I've set up my tests so that the constructor is the arrange and the act.
The methods are the asserts. Each method is a separate test case but the
class is only instantiated once. I ran into a case where I'd like to
pararmetize the constructor so I can run the same test with slightly
different data. Is there some other means to accomplish the same thing?

**Comment by plioi** [comment]
Unfortunately, not, though I see why you'd want it.

What we do have is [parameterized test methods]([http://fixie.github.io/docs/1.0/parameterized-test-methods/), where the inputs to the test method itself come from a "source" you define.

You've seen UsingFactory, and we have a related option of test construction frequency such as when you specify [CreateInstancePerCase](http://fixie.github.io/docs/1.0/test-lifecycle/).

In the past I've seen people employ CreateInstancePerClass (NUnit style), where the constructor does the arrange and the act, then the test methods are very small asserts.

I've also seen people use the more common CreateInstancePerCase (xUnit style), where very little goes on in the constructor and the test method does most of the work including parameterization.

I wonder, if your test class constructor only did the part that *doesn't* vary, could you combine CreateInstancePerClass with the method-level parameterization feature to approximate your ideal scenario?

**Comment by roend83** [comment]
What I like about this setup is that all assertions run on every test run
regardless of which ones fail. It sounds like I'd have to give that up. I
can support this with a base class and multiple subclasses. Not ideal, but
it will accomplish the same thing.

**Comment by plioi** [comment]
Closing as I believe this is possible in v2 now. Instead of calling the built-in TestClass.Construct() helper, you can construct the TestClass.Type however you like in the middle of an Execution implementation.
