### ISSUE TITLE
Running Tests in VS Compiled as x64

### ISSUE THREAD

**Issue by roend83** [fixie/fixie#178]
Does fixie support running x64 tests in the Visual Studio test runner?  I can't get VS to discover the tests.  I've tried changing the default processor architecture of the test runner to x64.

**Comment by plioi** [comment]
Which version are you running?

This sample project has worked for me, demonstrating x64 support: https://github.com/fixie/fixie.integration/tree/master/src/x64.Tests

How does your test project csproj compare to that one? https://github.com/fixie/fixie.integration/blob/master/src/x64.Tests/x64.Tests.csproj

In the latest alpha release, Test Explorer's own 32/64 bit setting should have no effect as described in the release notes: https://github.com/fixie/fixie/releases/tag/v2.0.0-alpha-0003

Test Explorer has always had bugs in which it gets very confused about what's going on. I recommend:

1. Close all instances of Visual Studio.
2. Delete the contents of %TEMP%\VisualStudioTestExplorerExtensions (this is a cache that gets messed up occasionally by VS)
3. Restart VS and rebuild the solution.

**Comment by roend83** [comment]
Deleting that cache folder fixed my issue.  I'm not sure what happened.
Thanks for the help.

**Comment by plioi** [comment]
No problem. That cache folder is very frustrating!
