### ISSUE TITLE
Discovery constructor requires `params` modifier to pass arguments

### ISSUE THREAD

**Issue by Suremaker** [fixie/fixie#185]
## Steps to Reproduce
Hello,
I have observed a bit strange behavior of the discovery convention.

Assuming project:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Shouldly" Version="3.0.0" />
    <PackageReference Include="Fixie" Version="2.0.0" />
    <DotNetCliToolReference Include="Fixie.Console" Version="2.0.0" />
  </ItemGroup>

</Project>
```

and class:
```c#
using System;
using Fixie;
namespace FixieDiscovery
{
    public class CustomDiscovery : Discovery
    {
        public CustomDiscovery(string[] args)
        {
            Console.WriteLine("Args: " + string.Join(", ", args));
        }
    }
}
```

When I run command: `> dotnet fixie -- arg1 arg2`
the arguments are not passed to the CustomDiscovery instance.

## Expected Behavior

```
Building FixieDiscovery...
  FixieDiscovery -> C:\tmp\FixieDiscovery\FixieDiscovery\bin\Debug\netcoreapp2.0\FixieDiscovery.dll
Running FixieDiscovery

Args: arg1, arg2
No tests found.
```

## Actual Behavior
```
Building FixieDiscovery...
  FixieDiscovery -> C:\tmp\FixieDiscovery\FixieDiscovery\bin\Debug\netcoreapp2.0\FixieDiscovery.dll
Running FixieDiscovery

Args:
No tests found.
```

## Workaround

To make it working I had to add `params` modifier like as follows:

```c#
using System;
using Fixie;
namespace FixieDiscovery
{
    public class CustomDiscovery : Discovery
    {
        public CustomDiscovery(params string[] args) // <-- see the params modifier
        {
            Console.WriteLine("Args: " + string.Join(", ", args));
        }
    }
}
```

**Comment by plioi** [comment]
This is an area that definitely deserves additional examples and explanation in the documentation.  However, the one example we have out there is worth contrasting with your sample code:

https://github.com/fixie/fixie/wiki/Custom-Command-Line-Arguments

In that example, the customization class has a constructor accepting `string[] include`, and the command line which populates it does so by taking the *name* of that argument into account:

`dotnet fixie --configuration Release -- --include LongRunning --include Integration`

The command line argument model binding takes `--key value` arguments and maps them to the corresponding named argument of the constructor. In the case of an array, the --key can be specified more than once like in this example. A bool named argument can be specified as true merely by including its --key.

The 'params' array argument is then reserved for folks who *do* want a catch-all for *positional* (iow unnamed) arguments.

There are many examples of different combinations and data types in the tests of the model binding feature: https://github.com/fixie/fixie/blob/master/src/Fixie.Tests/Cli/ParserTests.cs

If the model binding concept is too niche, and you really just want access to the original raw command line arguments, I'd try System.Environment.GetCommandLineArgs.

**Comment by Suremaker** [comment]
Thank you, I have missed the documentation for it. Now it is clear.
