### ISSUE TITLE
Enable test discovery in VS Code

### ISSUE THREAD

**Issue by seesharper** [fixie/fixie#187]
## Steps to Reproduce

* Create a new class library using `dotnet new classlib`
* Add required references in csproj file 

```
<!-- Example.Tests.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fixie" Version="2.0.0" />
    <PackageReference Include="Shouldly" Version="2.8.3" />
    <DotNetCliToolReference Include="Fixie.Console" Version="2.0.0" />
  </ItemGroup>

</Project>
```

## Expected Behavior

The run/debug commands to be available like when using xUnit

![image](https://user-images.githubusercontent.com/1034073/40536190-99410fca-600b-11e8-972f-e90c8784ce70.png)

## Actual Behavior

run/debug commands are not available.

What would it take to make this work? I'll be happy to contribute to this, but I simply don't know where to start :)

**Comment by plioi** [comment]
That's a great idea. I also don't know where to start. I wonder whether VSCode is ultimately using the same discovery/execution mechanism as Test Explorer (in which case we must be missing some detail that lets it detect it). For this xUnit behavior, did you have to install any xUnit or general testing extensions in VSCode?

**Comment by seesharper** [comment]
I believe this functionality comes with the C# extension and is backed by OmniSharp.

https://github.com/OmniSharp/omnisharp-vscode
https://github.com/OmniSharp/omnisharp-roslyn

https://github.com/OmniSharp/omnisharp-roslyn/tree/master/tests/OmniSharp.DotNetTest.Tests

@filipw Do you know how this works in more detail?

**Comment by plioi** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.DotNetTest/TestFrameworks/TestFramework.cs Looks like it's looking for well-known test attributes for the Big 3 frameworks, which makes a lot of sense, but could be a blocker.

As an experiment, could you add a fake Fact attribute to your project, with the right namespace: Xunit.FactAttribute? If you place such a lookalike on your Fixie tests, do they begin to get detected?

**Comment by filipw** [comment]
yes. OmniSharp exposes an extensibility point [ISyntaxFeaturesDiscover](https://github.com/OmniSharp/omnisharp-roslyn/blob/e18913e887144119c41d60f1842e49f8e9bfcf72/src/OmniSharp.Roslyn/Services/ISyntaxFeaturesDiscover.cs) which is used to locate tests. This happens through the test-specific implementation [TestFeaturesDiscover](https://github.com/OmniSharp/omnisharp-roslyn/blob/e18913e887144119c41d60f1842e49f8e9bfcf72/src/OmniSharp.DotNetTest/TestFeaturesDiscover.cs)

Then you just have different implementations for different test frameworks, that simply look at the syntax tree and/or semantic model and decide that, yes, this is a test i.e. https://github.com/OmniSharp/omnisharp-roslyn/blob/e18913e887144119c41d60f1842e49f8e9bfcf72/src/OmniSharp.DotNetTest/TestFrameworks/MSTestFramework.cs

I am not sure this should be added to the core of OmniSharp, but the implementations of `ISyntaxFeaturesDiscover` can also be built into external DLLs and loaded on OmniSharp startup by passing them in as startup arguments.

Also, I don't know enough about Fixie. Is it possible to decide that a test is a test from the semantic model?

**Comment by plioi** [comment]
By default, a method is a test if it's a public method inthe test project, in a class whose name ends with Tests.  However, users can customize that rule, and it's a *runtime* decision rather than something purely syntactic.

**Comment by seesharper** [comment]
@plioi Actually just declaring the attribute is enough 

```
using System;

namespace Xunit
{
    public class FactAttribute : Attribute
    {
    }
}
```

Then a test class like this 

```
namespace FixieTest
{
    public class SampleTests
    {
        [Fact]
        public void ShouldBeOk()
        {
            
        }
    }
}
```

![image](https://user-images.githubusercontent.com/1034073/40559787-2ee62d84-6058-11e8-815c-d0bab315838a.png)

Trying to run the test fails though 

```
Fixie 2.0.0
Processing /Users/bernhardrichter/GitHub/FixieTest/bin/Debug/netcoreapp2.0/FixieTest.dll
An exception occurred while test discoverer 'VsTestDiscoverer' was loading tests. Exception: Message transmission mode is not supported on this platform.

Total tests: 0. Passed: 0. Failed: 0. Skipped: 0
```

**Comment by plioi** [comment]
That message must be coming from outside of fixie. However, "on this platform" is an interesting part of the error message. Can you try targeting net452 or similar and seeing if that produces the same error? The VS side of test running treats .NET Core runs different from full desktop framework runs.

**Comment by seesharper** [comment]
Could this be it? 
https://github.com/dotnet/corefx/issues/25161

**Comment by seesharper** [comment]
I'll try it on Windows targeting the full framework

**Comment by plioi** [comment]
Oh, no. I *do* rely on PipeTransmissionMode.Message
https://github.com/fixie/fixie/blob/master/src/Fixie.VisualStudio.TestAdapter/VsTestDiscoverer.cs#L38

**Comment by seesharper** [comment]
Ah, Okay. Wonder what the other frameworks are doing on .Net Core

**Comment by seesharper** [comment]
Probably a good call leaving those hacks out. 👍 Could we do this interprocess communication using stdout?  Just thinking out loud here

**Comment by seesharper** [comment]
Something like `dotnet fixie --discover [pathToAssembly]`

I don't know if you are aware of this, but communicating over `stdout` is exactly how the C# extension talks to OmniSharp.Roslyn. 

https://github.com/OmniSharp/omnisharp-roslyn/tree/master/src/OmniSharp.Stdio

Just my two cents without at all looking into the details :)

**Comment by seesharper** [comment]
I'll be happy to take a look at the alternatives if you're interested 👍

**Comment by plioi** [comment]
I greatly appreciate it. At the end of the day, I have JSON messages that are sent and received between two processes. "Do this work please." "Ok, here are the results one at a time.... and now I'm done." The "Message" mode made it *easy* to send those back and forth in an appropriately-blocking way, but there's probably a way to accomplish the same in the other modes.

**Comment by seesharper** [comment]
@plioi FYI It works as expected in Visual Studio for Mac. Do they shim `PipeTransmissionMode ` to make that work?

**Comment by plioi** [comment]
That is *very* surprising. I thought there were operating system-level obstacles to supporting that mode.

**Comment by MarkusEischeid** [comment]
For your interest: Here https://github.com/xunit/visualstudio.xunit you can find the vscode integration for XUnit. Perhaps you can find something useful there.

**Comment by plioi** [comment]
@MarkusEischeid I believe that repo is only for Visual Studio integration (the Test Explorer window) rather than the similarly-named VS Code text editor.

**Comment by MarkusEischeid** [comment]
You are right. I thought it was for both Visual Sudio and vscode. Sorry.

**Comment by plioi** [comment]
Closing this issue for a few reasons:

* v3 no longer uses "Message" transmission mode reported above in conversation, which was problematic outside of Windows.
* v3.1 satisfies the .NET Test Adapter pattern and users have reported that visual test runner extensions made to speak the "dotnet test" protocol work in VS Code, giving an experience equal to the Visual Studio Test Explorer / ReSharper / Rider UI.
* Fixie test discovery is a runtime decision, not a source-only decision. Thankfully the above workaround to define your own xUnit-mimicking Fact attribute works. When I do so I can right click inside a test method, and the "Run Tests in Context" context menu item works. I think a custom Task invoking "dotnet fixie" would be nice, though, as it runs far faster than "dotnet test" and has cleaner output.
* I don't expect to have the resources for *VS Code specific* enhancements in Fixie, relying intead on the far reach that the .NET Test Adapter is now finally providing.
