### ISSUE TITLE
How can I execute test setup asynchronously?

### ISSUE THREAD

**Issue by Rookian** [fixie/fixie#190]
I would like to execute some async code before calling `@case.Execute(instance);`.
Right now I am doing the following:

```
InitializeDbs(container).GetAwaiter().GetResult();
@case.Execute(instance);
```

Is it possible to have an async version of
```
public interface Execution
{
  void Execute(TestClass testClass);
}
``` 
?

**Comment by plioi** [comment]
Not at the moment. Although generally it's inadvisable to force a Wait operation on a Task like that, (especially in web apps where we might hit a surprising deadlock), that's not the case here. We're in the extra simple "console app" async context which won't have that issue.

Test methods themselves can be marked as `async Task`, though. In that case, Fixie is really just doing the same kind of forced Wait as you're talking about here.

**Comment by Rookian** [comment]
Ok, it is not a problem and if I write `await Awaitable()` or `Awaitable().Wait()` is not a big difference.
