### ISSUE TITLE
Problems running fixie from command line

### ISSUE THREAD

**Issue by Dessyreqt** [fixie/fixie#194]
## Steps to Reproduce
run `dotnet fixie` from test project folder

## Expected Behavior
Fixie builds and runs tests

## Actual Behavior
Fixie builds the tests, but then returns the following:
```
Fatal Error: System.IO.FileNotFoundException: Could not find file 'C:\Users\Dessyreqt\AppData\Local\Temp\tmpDED4.tmp'.
File name: 'C:\Users\Dessyreqt\AppData\Local\Temp\tmpDED4.tmp'
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at Fixie.Console.Shell.msbuild(String project, String target)
   at Fixie.Console.Program.GetTargetFrameworks(Options options, String testProject)
   at Fixie.Console.Program.Main(String[] arguments)
```

I will note that I can observe the file being created and deleted. I am attempting to run this either as part of a build script or for coverage purposes. If there are better ways of addressing these, I would be happy to hear about them. In Fixie 1.0 there was a console application runner, but in Fixie 2.0 this appears to be the closest analog.

**Comment by plioi** [comment]
This is failing in an area that has been stable for other folks, so let's see what's going on in that part of the code.

First, `dotnet fixie` relies on msbuild to figure out what target frameworks your test project is targeting. We arrive at https://github.com/fixie/fixie/blob/bb44dc4ab27bab18ae930a791ce6103651bfdf74/src/Fixie.Console/Program.cs#L95 where we're about to ask msbuild to do that.

Then we come to https://github.com/fixie/fixie/blob/bb44dc4ab27bab18ae930a791ce6103651bfdf74/src/Fixie.Console/Shell.cs#L49 where we actually reach out to msbuild. Msbuild is a little weird in the way we can get information out of it. We're essentially querying your csproj for information, and the results are meant to go into the temp file you see being created/deleted.

So, this is a bit of a head-scratcher. We're calling Path.GetTempFileName() and then File.ReadAllLines(path) is throwing FileNotFoundException.

From the stack trace alone, that doesn't make much sense. Maybe it's more of a permissions issue.

Can we see a copy of your test project's csproj file, especially the parts about TargetFramework, TargetFrameworks, and NuGet packages?

**Comment by Dessyreqt** [comment]
Here is the project file (minus class & project references): [Project file on Pastebin](https://pastebin.com/bYUqNzrx)

**Comment by plioi** [comment]
Oh, I see. That looks like the more verbose pre-.NET-Core-era csproj format.

When .NET Core arrived, it came with some major changes to the csproj format, and for unit test frameworks in particular that imposed a pretty sharp set of restrictions. That applies even for projects that target the regular framework.

Fixie 1.x can work with that older style csproj, and Fixie 2.x can only be expected to work with the new style csproj. The new style includes the ability to install packages that extend `dotnet` with commands such as `dotnet fixie` for running from the console.

There is a slight chance you can run this as-is by treating the test project's own build output as a console application. If your test project resulted in an exe, you can try to invoke it directly. This is not a supported scenario, though.

See the docs' Quick Start for an example of what a Fixie 2.x test project would look like: https://github.com/fixie/fixie/wiki#quick-start

**Comment by Dessyreqt** [comment]
I can confirm that upgrading to the new project format makes the command line work. Thanks!

**Comment by plioi** [comment]
Great! Thanks for confirming.
