### ISSUE TITLE
Execute Unit Tests in dll as opposed to project

### ISSUE THREAD

**Issue by Dessyreqt** [fixie/fixie#195]
When I run `dotnet fixie`, it works if I'm working in a directory that has a test project. In Fixie 1.x, it was possible to run `Fixie.Console.exe` targetting the dll output of the test project. Is there a similar method in 2.x? I understand there is the `--no-build` option, but it still requires the test project to exist before running.

This might also be helpful for running code coverage.

**Comment by plioi** [comment]
A pivotal difference between Fixie 1 and 2 is that in 2, your test assembly *is* the console runner for itself. The only thing that `dotnet fixie` does is loop through the project's TargetFramework or TargetFrameworks to locate the implied bin/etc/ folders and invoke them one at a time. If you want to run a particular test project's build output, just run it like it's a console program.

**Comment by Dessyreqt** [comment]
Very cool. So to be clear (for anyone else that may come along and read this), you can simply add `<OutputType>Exe</OutputType>` to your test project file (it was missing from mine) to create the executable and run that independently via a build script or coverage tool or whatever.

**Comment by plioi** [comment]
You might not have had to actually put that OutputType in the csproj explicitly. When you say `<PackageReference Include="Fixie" Version="2.0.2" />`, we apply that to your project automatically: https://github.com/fixie/fixie/blob/master/build/Fixie.targets#L5

**Comment by Dessyreqt** [comment]
I just verified with another project I'm working on that upgrading from 1 to 2 doesn't set this flag in the project.

**Comment by plioi** [comment]
It wouldn't literally appear in the csproj. Nuget packages that include these "targets" files have the *effect* of copying the XML into the csproj, but do so as more of a runtime thing than an actual update file. The resulting file in the build output is likely an executable (though surprisingly might still wind up with a *dll extension).  If you have a tool like ReSharper you'll actually be able to navigate to the Main method, which is provided by the NuGet package as well.
