### ISSUE TITLE
Unable to reference the Fixie.Console (v2.1.1) NuGet package.

### ISSUE THREAD

**Issue by lesair** [fixie/fixie#200]
## Issue Summary
Unable to add the Fixie.Console (v2.1.1) NuGet package reference as described in the [Quick Start guide](https://github.com/fixie/fixie/wiki#quick-start).

## Issue Context
* Code editor: Visual Studio 2019.

## Steps to Reproduce
1. Add a new test project using the "MSTest Test Project (.NET Core)" template.
![image](https://user-images.githubusercontent.com/22417425/64076529-af97ea80-cc8b-11e9-8a8e-8cd36ffbaec4.png)
![image](https://user-images.githubusercontent.com/22417425/64076544-cb9b8c00-cc8b-11e9-9532-8f74b129219b.png)
2. Add a Fixie NuGet package (v2.1.1) reference to the test project;
`Successfully installed 'Fixie 2.1.1' to UnitTestProject1`
![image](https://user-images.githubusercontent.com/22417425/64076597-83c93480-cc8c-11e9-9efc-add45ffdb52c.png)
3. When attempting to add the reference to the Fixie.Console (v2.1.1) NuGet package, an error is thrown and the reference cannot be added:
`Package 'Fixie.Console 2.1.1' has a package type 'DotnetCliTool' that is not supported by project 'tests\UnitTestProject1'.`
![image](https://user-images.githubusercontent.com/22417425/64076637-d60a5580-cc8c-11e9-9bb7-2f69d3855383.png)

## Expected Behavior
References to the NuGet packages Fixie and Fixie.Console are added successfully.

## Actual Behavior
An error is thrown when attempting to add a reference to the Fixie.Console NuGet package:
P`ackage 'Fixie.Console 2.1.1' has a package type 'DotnetCliTool' that is not supported by project 'tests\UnitTestProject1'.`

**Comment by lesair** [comment]
Never mind, I was able to use Fixie by creating the project with the dot net CLI command
`dotnet new classlib`

Then manually editing the .csproj file, putting the following content:
```
<!-- Example.Tests.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.2</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fixie" Version="2.1.1" />
    <PackageReference Include="Shouldly" Version="3.0.2" />
    <DotNetCliToolReference Include="Fixie.Console" Version="2.1.1" />
  </ItemGroup>

</Project>
```

Regards.

**Comment by plioi** [comment]
That's right. The MSTest project template would have several things in it that would conflict with non-MSTest frameworks like Fixie. Also, the NuGet package UI has (at least in the past), had no support for "Tool" packages like Fixie.Console.  Really, with the advent of .NET Core, the MS folks want everybody to start getting used to just editing csproj by hand.

**Comment by lesair** [comment]
Thank you for the explanation, @plioi .
