### ISSUE TITLE
Fixie sample application for demonstration purposes.

### ISSUE THREAD

**Issue by lesair** [fixie/fixie#201]
## Issue description
For newcomer and seasoned Fixie users, it would be great to have a sample application wrote by the masters that would serve as a navigational beacon about Fixie intended usage, best practices and techniques. I asked Jimmy Bogard about the possibility that he incorporates Fixie as the testing framework in his amazing [Contoso University sample app](https://github.com/jbogard/ContosoUniversityDotNetCore-Pages). Unfortunately, Jimmy replied that [none of his clients used Fixie](https://github.com/jbogard/ContosoUniversityDotNetCore-Pages/issues/18), and his sample app was intended to show his techniques and strategies on a typical project (which uses xUnit instead).

@plioi perhaps you have something you could share with us. If not, I could contribute by forking Jimmy's sample app and incorporate Fixie instead of xUnit, but I would require your guidance.

## Justification for this request
As mentioned in the blog post "[Integration Testing with xUnit](https://jimmybogard.com/integration-testing-with-xunit/)": 

> ...I had given up on xUnit **in favor of Fixie** because of the flexibility that Fixie provides.

and

> ...while it's feasible to write tests in this way, I'd suggest avoiding it... Instead, either use a framework more suited for this style of tests (**Fixie** or any of the BDD-style libraries)...

**Comment by plioi** [comment]
I have a sample app in mind that could be made public for this purpose. It would be the modern improvement upon the old advice seen in https://lostechies.com/patricklioi/2016/01/27/powerful-integration-testing

**Comment by lesair** [comment]
That would be awesome.

I make myself available for help if you want, Patrick.

**Comment by plioi** [comment]
See https://github.com/fixie/fixie.demo

I'll be adding some instructional content to the README soon.

**Comment by lesair** [comment]
Awesome, @plioi .

The app it's working fine
![image](https://user-images.githubusercontent.com/22417425/66448109-1ab8a780-ea16-11e9-9cec-4d5ebe44015b.png)

Now I'm trying to run the tests on Fixie, thank you.

**Comment by isaac-gardner** [comment]
Hi @plioi

What happened to your fixe.demo repository, it was awesome.

Lucky I cloned it somewhere local, I should be able to find it. Sad to see it missing from github thought. I thought the code was `amazing`.

Regards,
Isaac

**Comment by plioi** [comment]
@isaac-gardner It was essentially replaced by a demo over in my own account: https://github.com/plioi/web-app-patterns

This was a from-scratch redo to demonstrate the latest iteration of what I'd really do on a modern .net project.

Be sure to not only peek at the latest commit, but pull down the history and see the flow from one git tag to the next:

`baseline` has no front end but establishes the main operations of the demo application including a lot of test infrastructure that should look familiar to the old fixie demo repo.

`net6.0-mvc` Adds a simple mvc front end, mostly so I could show folks what changes when you switch to blazor.

`net6.0-blazor` Drops the MVC front end and replaces with blazor. Note there are some neat things going on here with client side vs server side validations, all through FluentValidation, in such a way that I could avoid having to duplicate rules on the front and back end.

`net6.0-minimal-api` Takes that and pivots from older controllers to newer minimal api. Things actually got unpleasantly verbose here, so...

`net6.0-simplify-vertical-slices` gets a little nuts to reduce that verbosity back to something I'd want to actually write.

The commit by commit history might be worthwhile to follow step by step during the branches that made those last two tags.
