### ISSUE TITLE
Fixie console doesn't appear to work using "dotnet fixie" as per https://github.com/fixie/fixie/wiki/Test-Runner-Integrations

### ISSUE THREAD

**Issue by piriej** [fixie/fixie#205]
## Steps to Reproduce
Using Visual Studio 16.3.2, create a base test application as per https://github.com/fixie/fixie/wiki#quick-start

(note: as Fixie will not install via package manager)
  * dotnet add package Fixie
  * dotnet add package Fixie.console
  * dotnet add package fluentassertions

<B>dotnet list package</B>
```
   [netcoreapp3.0]:
   Top-level Package       Requested   Resolved
   > Fixie                 2.2.0       2.2.0
   > Fixie.console         2.2.0       2.2.0
   > fluentassertions      5.9.0       5.9.0
```
<B>dotnet fixie</B>
```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-fixie does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

<B>dotnet -h</B>
```
...
Additional commands from bundled tools:
  dev-certs         Create and manage development certificates.
  fsi               Start F# Interactive / execute F# scripts.
  sql-cache         SQL Server cache command-line tools.
  user-secrets      Manage development user secrets.
  watch             Start a file watcher that runs a command when files change.

```

## Expected Behavior
Runs the tests

## Actual Behavior
Cannot find the "dotnet fixie" command

**Comment by piriej** [comment]
... Sorry I believe this works now with: 
<B>dotnet test</b>

**Comment by plioi** [comment]
I recommend sticking to the specific guidance in the Quick Start.

`dotnet add package` doesn't support adding the special "tools" packages, so if you compare your csproj content to that in the quick start, I think you'll see that `dotnet add package` added a `PackageReference` rather than a `DotNetCliToolReference`.

`dotnet test` is supported but I don't recommend it. It clutters the output and runs far slower.

`dotnet fixie`, per the Quick Start, would be expected to work *in the context of the project folder*. From the Quick Start:

    $ cd Example.Tests
    $ dotnet fixie

**Comment by piriej** [comment]
Thanks as always Patrick

**Comment by piriej** [comment]
Thanks again,
The tests now run in the Azure pipeline as described. I notice the image you posted on https://github.com/fixie/fixie/wiki/Test-Runner-Integrations has the same issues I am experiencing, in that the test. They seem to run indefinitely and don't update the test summary.

![image](https://user-images.githubusercontent.com/13327469/66615195-5ff7f780-ec17-11e9-85ca-4ba97cf9e3fa.png)

Any thoughts?

**Comment by plioi** [comment]
Sorry, I'm a little confused. You say you are seeing the same thing in my image, but the images you posted both look quite different from my experience. Where in the Azure DevOps UI are you clicking in order to see those two screens?

**Comment by piriej** [comment]
Sorry for the confusion, MS have changed up the UI a bit. This is using a YAML multi staged pipeline(though I don't think that matters):

https://tfsprodeausu7.visualstudio.com/YOURINSTANCE/YOURPROJECT/_build/results?buildId=4712&view=ms.vss-test-web.build-test-results-tab

and

https://tfsprodeausu7.visualstudio.com/YOURINSTANCE/YOURPROJECT/_testManagement/runs?_a=runQuery

In reference to your image, My understanding is that this icon infers that the job is still running:
![image](https://user-images.githubusercontent.com/13327469/66618924-cc2e2780-ec26-11e9-8246-ef9a83f7c16b.png)

**Comment by plioi** [comment]
Oh, wow, thanks! I hadn't realized that's what the icon meant. Looks like I'll need to study the API some more. I'll create a separate Issue for that to track progress.

**Comment by plioi** [comment]
FYI, I've fixed this in `develop` branch and it'll be available in the next release later this month.
