### ISSUE TITLE
Project Planning.

### ISSUE THREAD

**Issue by chan18** [fixie/fixie#251]
Hi, Can you please list down the things you want to be completed this week? Or we can use https://github.com/features/project-management To plan things whatever you prefer.

you can create tickets and assign them to me that is faster and easier for me to get started I think.

Thank you,
Chandra Kanth.

**Comment by plioi** [comment]
I'd like to keep project management activities to a minimum, so we can do this simply one thing at a time as pull requests.

I sent Steven a more detailed list on Feb 4, so be sure to get a copy of that for expectations. Let's focus first on the fixie.benchmark repo from that list.

**Comment by plioi** [comment]
Closing this since version 3 has been released. Thanks for your assistance in the early (and problematic!) beta builds.
