### ISSUE TITLE
dotnet fixie build fails, but exit code is 0

### ISSUE THREAD

**Issue by m-villanueva** [fixie/fixie#252]
## Steps to Reproduce
Run a test within a .csproj that has a compilation error using the `dotnet fixie` command

## Expected Behavior
The command should exit with a non-zero error code

## Actual Behavior
The command exits with code 0 and TeamCity build does not fail

![image](https://user-images.githubusercontent.com/5473685/109350661-bd044580-782c-11eb-81ca-883c827c2776.png)

The work around in TeamCity is to enable other failure conditions, but the error feedback is not as good.

**Comment by plioi** [comment]
Interesting! Thanks for the feedback.

I think that the following can get you to a better TeamCity experience in the short term, without having to adjust failure conditions:

When `dotnet fixie` is given the --no-build argument, it'll skip trying to run "dotnet build" for you implicitly. It's likely the implicit build that is confusing the return code.

When you do include the --no-build argument, it assumes that you have already run "dotnet build" shortly before that. That'll let you check for meaningful return codes from each step without first having to wait for a bug fix.

I do so here in fixie's own build script: https://github.com/fixie/fixie/blob/main/build.ps1#L14-L15

**Comment by plioi** [comment]
I'm still unable to reproduce this. When I attempt to, `dotnet fixie` properly detects a build failure and returns its 'fatal error' exit code, not 0. Here is the relevant code snippet from the implementation:

```cs
if (options.ShouldBuild)
{
    WriteLine($"Building {Path.GetFileNameWithoutExtension(testProject)}...");

    var exitCode = RunTarget(testProject, "Build", options.Configuration);
                    
    if (exitCode != 0)
    {
        Error("Build failed!");
        return FatalError;
    }
}
```

Based on the screenshot of your build script output, I suspect that the "Build failed!" is an accurate statement based on the above correct exit code, but that "Process exited with code 0" is a TeamCity issue in its ability to detect the exit code *of the build script itself*. I've run into that before as seenhere: https://youtrack.jetbrains.com/issue/TW-21554/Powershell-runner-script-fails-but-the-build-succeeds-Process-exited-with-code-0
