### ISSUE TITLE
Rider VSTest plugin *should* find Fixie tests, but doesn't

### ISSUE THREAD

**Issue by garoyeri** [fixie/fixie#256]
## Steps to Reproduce

1. Run Rider (either regular or EAP version)
2. Setup Fixie 3.0.0 and a simple test project as per the instructions (ensure that you are referencing the `Fixie.TestAdapter` package)
3. Add at least one test
4. Open up Rider
5. Ensure that VSTest support is turned on: <https://www.jetbrains.com/help/rider/Reference__Options__Tools__Unit_Testing__VSTest.html>
6. Rebuild the solution
7. Check the unit test / explorer tab to see the list of tests.

## Expected Behavior

I should see a list of tests.

## Actual Behavior

No tests are found in the solution. Running `dotnet test` or `dotnet fixie` does cause the tests to execute. The documentation in Rider makes it seem like this should all work. And the Fixie Test Adapter URI is `executor://fixie.testadapter/` which is not in the "Ignore" list:

![image](https://user-images.githubusercontent.com/265132/127692992-ae962094-a7a8-4013-9893-7301275717e5.png)

**Comment by plioi** [comment]
Our understanding is the JetBrains presentation of the feature here is misleading, that all one would need is a TestAdapter.

As background: any integration with VS Test Explorer comes in the form of of a "TestAdapter" dll (which we do provide), and "dotnet test" works by invoking that same integration. Think of "dotnet test" as a headless invocation of the Test Explorer experience. So, that's two votes in favor of "Fixie implemented its TestAdapter correctly". We also include a URI like those in your screenshot.

In the early days of .NET Core, there was a blog post and some documentation from JetBrains suggesting that anything that integrates with `dotnet test` would Just Work here too, but that was right *before* Microsoft made a very large pivot in the way `dotnet test` would work.

More recent documentation hints at an extra hurdle to cross: https://www.jetbrains.com/help/resharper/sdk/Features/UnitTest/DotNetCore.html describes the idea that ReSharper (and I presume Rider) can lean on "dotnet test" as originally promised, but (emphasis added):

> Map dotnet test IDs to ReSharper elements. When a test is discovered, it is reported with an ID that is relevant only to the test runner from the NuGet package. **A ReSharper test provider must map between this ID and a ReSharper unit test element.**

The test ID in question is probably the method-full-name string we are providing to VSTest, which helps Test Explorer show the tree of tests. It's not so much an arbitrary ID in fact as it is just a method name, so it's a little surprising that the docs here describe it as being opaque.

That makes it sound like:

1. Our VSTest plugin is important, but not enough.
2. We still have to build a whole JetBrains-style plugin ourselves.
3. That plugin's job is to take one string per discovered test and map that to JetBrains' understanding of type/method.

At least that was my understanding before your screen shot. Your screen shot and the listing of found-URIs makes me wonder why we're not even showing up in that list. Are we missing some small thing that would make us finally visible? Or do we have to make a whole plugin for one string.Split()-and-map.

I'd like to hear from someone in the know about this "Enable VSTest adapters support" option for the real answer. @khalidabuhakmeh we were talking about this recently on twitter. Is there someone very close to the Rider + TestAdapter detection who could shed some light on the shortest path to success here? If Rider is meant to just work with any TestAdapter, I'd prefer the shorter path to getting that going than to make a whole plugin.

**Comment by khalidabuhakmeh** [comment]
Leaving a comment here letting you know I've read the issue. I'll try to find folks inside JetBrains that can give answers and possibly help.

**Comment by plioi** [comment]
Much appreciated!

**Comment by garoyeri** [comment]
On a similar note, using VS Code with the [.NET Core Test Explorer](https://marketplace.visualstudio.com/items?itemName=formulahendry.dotnet-test-explorer) extension will discover and execute Fixie tests using `dotnet test`.

**Comment by khalidabuhakmeh** [comment]
So It does work, you folks may be missing a reference to [`Microsoft.NET.Test.Sdk`](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk), and also be sure to **enable VSTest adapters support** in the settings of Rider.

![Screenshot 2021-07-30 at 16 23 15](https://user-images.githubusercontent.com/228256/127707920-7debae13-4de3-4983-9126-1cee82c31eec.png)

Here are the results of the tests after I run them.

<img width="462" alt="Screenshot 2021-07-30 at 16 25 08" src="https://user-images.githubusercontent.com/228256/127708100-d9f4ca22-41dd-4848-92bb-e545763e0bbd.png">

**Comment by plioi** [comment]
Wow, ok. That's a HUGE help. It might pose a challenge, but on my end not JetBrains'. We've dealt with that SDK package differently than the other frameworks. I'll mull it over soon. 

🎉 Hope!

**Comment by garoyeri** [comment]
I noticed this warning though when I add the package reference:

```
Fixie.Main.cs(12, 32): [CS8892] Method 'TestProjectEntryPoint.Main(string[])' will not be used as an entry point because a synchronous entry point 'AutoGeneratedProgram.Main(string[])' was found.
```

That might explain which `Main` ends up getting precedence.

**Comment by garoyeri** [comment]
Also interesting: when I run:

```
dotnet clean
dotnet fixie path/to/my/testproject
```

I get the warning during compilation as well (which is expected) but the tests still run fine in Fixie.

**Comment by plioi** [comment]
Oh, ok. That actually lines up with my understanding. 

The Test SDK introduces an empty Main() method, I am guessing in order to prevent people from ever trying to make a test project target only NetStandard, which presumably isn't "real" enough to be a test project.

Fixie's console runs rely on a *different*, non-empty Main() being injected, and so that's why I've deliberately avoided the SDK reference so far. I accomplish the same things, except provide my own Main(). I was actually expecting a compiler *error* but by coincidence my Main() is async and the compiler is choosing a winner.

So, I bet the test runs in the IDE work, and I wonder what goes wrong at "dotnet fixie ..." time since the wrong Main() won.

**Comment by plioi** [comment]
I'm surprised by the console run working. I'll have to dig into the details. Hopefully I can either be *more* like the SDK to be recognized, or start to include it but suppress the poor Main() for my own exclusively.

**Comment by estrizhok** [comment]
@plioi I guess the requirement to have `Microsoft.NET.Test.Sdk` referenced comes from the fact nearly all tests projects targeting .netcore & vstest have that one nuget. (Actually Fixie is the first framework I see that does not reference it) Apparently, what we really should have checked for is `Microsoft.TestPlatform.TestHost`. We could definitely change that, that would be proper, and you wouldn't have to do anything. Although, not in 21.3. That ship has already sailed.

**Comment by plioi** [comment]
Good to know, @estrizhok. I'll see if there are some easy moves to make on my end, too. You probably already saw I'm bringing in Microsoft.TestPlatform.TestHost as a dependency, so we're on the same page.

**Comment by plioi** [comment]
The SDK applies this to all test projects:

```xml
<Project InitialTargets="GenerateProgramFile" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!--
    Output type for .NET Core test projects should be exe.
    https://devdiv.visualstudio.com/DevDiv/_workitems?id=375688&_a=edit
  -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <GeneratedProgramFile Condition="'$(GeneratedProgramFile)' == ''">$(MSBuildThisFileDirectory)Microsoft.NET.Test.Sdk.Program$(DefaultLanguageSourceExtension)</GeneratedProgramFile>
    <GenerateProgramFile Condition="'$(GenerateProgramFile)' == ''">true</GenerateProgramFile>
  </PropertyGroup>

  <!--
    ============================================================
    GenerateProgramFile
    Generates Program file which contains the Main entry point
    ============================================================
  -->
  <Target Name="GenerateProgramFile"
          Condition="'$(GenerateProgramFile)' == 'true'">

    <ItemGroup Condition="'$(Language)' == 'VB' or '$(Language)' == 'C#'">
      <Compile Include="$(GeneratedProgramFile)"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Language)' == 'F#'">
      <ProgramCompiles Include="@(Compile)" Condition="'%(Identity)' == 'Program.fs'" />
      <CompileAfter Include="$(GeneratedProgramFile)" Condition="@(ProgramCompiles-&gt;Count()) == 0" />
    </ItemGroup>

    <Warning Condition="@(ProgramCompiles-&gt;Count()) != 0" Text="A 'Program.fs' file can be automatically generated for F# .NET Core test projects. To fix this warning, either delete the file from the project, or set the &lt;GenerateProgramFile&gt; property to 'false'." />

  </Target>

</Project>
```

So, the first thing I'll need to try on my end is to include this SDK *but also* ensure that I say ` <GenerateProgramFile Condition="'$(GenerateProgramFile)' == ''">false</GenerateProgramFile>` *before* this SDK code applies, so it'll naturally skip it.

**Comment by plioi** [comment]
Some nice progress over here: https://github.com/fixie/fixie/pull/258

I've got things working with an alpha build in ReSharper, though Rider's not reacting to it yet.

One *possible* difference between this and your successful proofs of concept above is that in the case of my alpha build, the Fixie.TestAdapter package *itself* is the one bringing in the important Microsoft.NET.Test.Sdk package, and I'm bringing in version 16.10.0 which is pretty recent.

**Comment by plioi** [comment]
Closed by #258 and released in [v3.1.0](https://github.com/fixie/fixie/releases/tag/3.1.0).

**Comment by khalidabuhakmeh** [comment]
YAY! Awesome news. If you have a tweet saying it works in Rider, I'd be happy to share and RT the news.

**Comment by plioi** [comment]
@khalidabuhakmeh Sure thing https://twitter.com/plioi/status/1423658244266987530
