### ISSUE TITLE
Support for Verify

### ISSUE THREAD

**Issue by SimonCropp** [fixie/fixie#271]
@plioi are you interested in working together to get Verify and Fixie to play nice together?

https://github.com/VerifyTests/Verify

**Comment by plioi** [comment]
I'm intrigued, and I'm having to devote a lot of time to other things for a while :(

My most relevant contribution in the short term could be some discussion here. Scanning your readme, it looks like you release test framework specific adapters, so our goal might be One More Like Those?

Most of Fixie's design can be compared to xUnit and NUnit, so it might help to catch me up in terms of those two integrations: what all did you need to hook into for xUnit and NUnit? That might indicate which Fixie customization hooks will come in handy.

**Comment by plioi** [comment]
A deliberately funky question that might help catch me up on the concepts could be, "If there were no attempt at an integration, and you just tried to use Verify from within a Fixie test, what would go wrong?"

**Comment by SimonCropp** [comment]
> If there were no attempt at an integration, and you just tried to use Verify from within a Fixie test, what would go wrong?

So the Verify snapshot file naming needs a few things to be able to support a test framework 

 * The MethodInfo of the current test
 * the current test file path. can be work around by  passing in a `CallerFilePath` on the verify call
 * the parameter values for a parameterized test. can be worked around by forcing people to call an extra method to pass through the parameters. This is not ideal, but it is the approach the xunit integration uses
 
 So does fixie some kind of context api that exposes any of the above? For other libs the following approaches are used

 * xunit: a `BeforeAfterTestAttribute` attribute to capture the method info
 * nunit: via using the `TestContext.CurrentContext` static state
 * mstest: requirign a base class that has a `TestContext` state property
 * Expecto has no state object so we force users to explicitly define the name, but that is cumbersome, and means a subset of the Verify features cannot be used.

If fixie doesnt expose some kind of context, could have a go at  PR that adds one
