### ISSUE TITLE
How to access commandline args in 

### ISSUE THREAD

**Issue by StevenTCramer** [fixie/fixie#272]
The wiki says: "A discovery or execution customization class can access arbitrary command line arguments."

But yet it isn't apparent to me how this is done?

I want to pass in a --tag xyz and then filter all my tests based on tag

How does the discovery/execution class get access to the environment so I can then access command args?

**Comment by plioi** [comment]
In this wiki code snippet, this is the CustomArguments property on the TestEnvironment passed to your TestProject.

There's another example over here https://github.com/fixie/fixie.integration/blob/b16078e68c8ddb88c919bea86dbf09b837e72720/src/CustomConvention.Tests/TestingConvention.cs

The `TestEnvironment` passed into `TestProject.Configure(...)` was needed by the example `CustomDiscovery`, passed along to the `CustomDiscovery` constructor.

**Comment by plioi** [comment]
I think you'll get the same thing via https://docs.microsoft.com/en-us/dotnet/api/system.environment.getcommandlineargs?view=net-5.0 though in this case your first array item will be a little funky.

**Comment by StevenTCramer** [comment]
So I have to pass to the constructor myself from the TestProject... 

the following then won't work

  public void Configure(TestConfiguration aTestConfiguration, TestEnvironment aTestEnvironment) =>
      aTestConfiguration.Conventions.Add<TestDiscovery, TestExecution>();

**Comment by plioi** [comment]
That Add method has overloads. The <T1, T2> flavor is a convenience overload for when there's nothing interesting to pass to the constructors. If you want the brevity of the <T1, T2> overload then I'd reach for `Environment.GetCommandLIneArgs()` from inside your custom discovery/execution.

**Comment by plioi** [comment]
You're really just arriving here when you call Add: https://github.com/fixie/fixie/blob/main/src/Fixie/ConventionCollection.cs

**Comment by StevenTCramer** [comment]
ok so just as easy to construct myself like you did in the integration link.  Thanks.  I was thinking they might be constructured with a ServiceCollection container or something.  Thanks!
