### ISSUE TITLE
Fixie should report the names of the convention(s) that cause a test to be discovered/run

### ISSUE THREAD

**Issue by JohnStov** [fixie/fixie#28]
I can imagine a scenario where you have multiple conventions, and you need to find out which convention or conventions caused your test to be detected. Maybe because you want to remove that convention...

The convention name(s) could be displayed as part of the test logging information, and also in any visual test discovery mechanism (like the forthcoming ReSharper test runner).

**Comment by plioi** [comment]
Closing this as it is no longer applicable in Fixie 2.0 rc 1. What was once a Convention subclass for which there could be many, the new Execution customization hook appears at most once per test assembly (those wanting multiple can accomplish the same with some conditional logic in their new Execution implementation).
