### ISSUE TITLE
Feature Request: Manually "Start" a test

### ISSUE THREAD

**Issue by LwsSt** [fixie/fixie#295]
I'm creating a test pattern on top of Fixie for use with some BDD-style tests.

The way I'm planning on implementing this is by having each test as a 'step' and a class being the full test:

```csharp
class MyTest
{
    [Step(1)]
    void DoThing1() { }

    [Step(2)]
    void DoThing2() { }

    [Step(3)]
    void DoThing3() { }
}
```

In the execution, I order all the tests by the `StepAttribute` and execute them.

One feature I'd like to have, is the ability to return test data from 1 step for use in the next.

```csharp
class MyTest
{
    [Step(1)]
    int DoThing1() { }

    [Step(2)]
    void DoThing2(int i) { }
}
```

Fixie provides all the tools (extension methods, etc) that make this all easily doable.

_However_, I run into an issue because `Run` doesn't give the return result of the invoked test, so I have to use `Call` instead. This is a problem because `Run` sends a `TestStarted` message to the reporter, and there doesn't appear to be a way to invoke this manually (like `Test.Pass`, `Test.Fail`, etc).

So this could be fixed in 2 ways:
1. Include the method return object in `TestResult.Passed`
1. Add `Test.Start` which only reports the start of a test, but doesn't invoke the method.

**Comment by plioi** [comment]
Fixed in #305 and available in v3.4.0. Please see that PR description for a detailed example with context, but not surprisingly it matches your suggestion: `await test.Start();`
