### ISSUE TITLE
Does Fixie supports test filtering when using `dotnet test`?

### ISSUE THREAD

**Issue by MangelMaxime** [fixie/fixie#352]
Hello,

I found that Fixie support test filtering when running `dotnet fixie`. However, most of Test Explorer use TRX files or `dotnet test` to run their test.

Does Fixie supports filtering via `dotnet test`?

It seems like each frameworks decide how they want to implement that said filtering: https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest

**Comment by plioi** [comment]
The existence of the `Fixie.TestAdapter` package not only enables Test Explorer integration, it also provides at least some `dotnet test` support, though I'm unsure if the `dotnet test` filtering arguments would have an effect. You'd have to try that out. I don't go out of my way to support `dotnet test`.

Here is the documentation on `dotnet fixie`'s own filtering concept: https://github.com/fixie/fixie/wiki/dotnet-fixie#filtering-with---tests

Additionally, depending on what kind of filtering you want, you might want to look at this sample project: https://github.com/fixie/fixie.integration/tree/main/src/CustomConvention.Tests .  In here, you'll see a custom 'category' attribute filtering scheme with a corresponding custom command line argument for `dotnet fixie`. The pivotal part of the customization logic is here https://github.com/fixie/fixie.integration/blob/main/src/CustomConvention.Tests/TestProject.cs#L42

**Comment by MangelMaxime** [comment]
Thanks for the explanation I will have a look at it.
