### ISSUE TITLE
Support for delegates

### ISSUE THREAD

**Issue by copypastedeveloper** [fixie/fixie#5]
Add support for using delegates as steps of a test.  using delegates for setup, teardown, test methods, and method execution.  The end goal is to be able to support a format similar to MSpec.

**Comment by derekgreer** [comment]
boo!

**Comment by derekgreer** [comment]
This is an old issue, but it seems the latest version still only supports tests derived from methods.  

 I really love the convention-based approach you took with Fixie.  It is a bit ironic, however, to have some area that's opinionated in this way when the defining characteristics of the framework really is that you can define your own conventions.

I'm an advocate of the context-specification approach to BDD and have always liked the low-noise expression that results from its use of delegates to explicitly support what is effectively the Arrange/Act/Assert pattern.    With this one shortcoming, the syntax MSpec uses can be replicated exactly with Fixie.

I'd like to ask that you reconsider adding this feature.  From briefly looking through the code, it doesn't look like it would be a significant change to the code base.
