### ISSUE TITLE
TargetParameterCountException during test execution

### ISSUE THREAD

**Issue by JonasSamuelsson** [fixie/fixie#74]
- create new project (vs2013.4)
- add fixie nuget package (0.0.1.229)
- add the following code

```
public class Convention : Fixie.Convention { }

public class TestClass
{
    public void TestMethod()
    {
        var s = string.Empty;
        var func = new Func<string, string>(_ => s);
    }
}
```

results in

```
c:\dev\FixieBug>packages\Fixie.0.0.1.229\lib\net45\Fixie.Console.exe FixieBug\bin\Debug\FixieBug.dll
------ Testing Assembly FixieBug.dll ------

Test 'FixieBug.TestClass+<>c__DisplayClass1.<TestMethod>b__0' failed: System.Reflection.TargetParameterCountException
Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Fixie.Internal.Behaviors.InvokeMethod.Execute(Case case, Action next)

1 passed, 1 failed, took 0.00 seconds (Fixie 0.0.1.229).
```

**Comment by MaherJendoubi** [comment]
How did you reproduce the problem, please?

**Comment by plioi** [comment]
@MaherJendoubi I'm sorry, I don't understand the question.  Are you having this problem with Fixie?  If so, I recommend upgrading.  It's been fixed in a more recent version.

If you're instead facing a *similar* exception in a *different* project, I'll need to know more in order to know what to suggest.

You can see where I fixed this Fixie bug here: 841d5faff541f09c30ca14758322889c0c1b49dc I fixed it by looking for whether or not a type has [CompilerGeneratedAttribute] on it, and ignored those.

**Comment by MaherJendoubi** [comment]
Thank you for the feedback @plioi and excuse me for being too late to reply you!
Actually, I am facing a similar exception in a different project. I am suspecting this chunck of code:

Object[] xmlParam = null;
            if (context.Request.InputStream.Length > 0)
            {
                xmlParam = new Object[1];
                xmlIn = XmlTools.getXmlFromHttpHeader(context.Request);
                xmlParam[0] = xmlIn;
            }
But I can't till the moment reproduce the bug..

**Comment by plioi** [comment]
@MaherJendoubi I'm afraid I don't see anything in that code snippet that looks like it's related to the Fixie issue above.  I suggest posting your exception and associated code to stackoverflow.com to ensure a better chance of getting some assistance.
