### ISSUE TITLE
Incorrect Xml reports for NUnit and XUnit

### ISSUE THREAD

**Issue by LodewijkSioen** [fixie/fixie#75]
I'm using [AppVeyor](http://www.appveyor.com/) for CI and when I tried to upload the testresults of my project during the build, I got errors. I reported them and they let me know that there were [problems with the Xml files](http://help.appveyor.com/discussions/problems/1235-uploading-fixie-testresults-as-nunit-or-xunit-gives-500-error):

> TestResult.AsXUnit.xml - root element must be ``<assembly>``, not ``<assemblies>``. See this article: https://xunit.codeplex.com/wikipage?title=XmlFormat

> TestResult.AsNUnit.xml - ``test-suite`` element doesn't contain ``type`` attribute.

**Comment by LodewijkSioen** [comment]
First of all: happy new year!
Secondly: congratulations on Fixie 1.0!

Lastly: I updated my repo. Is this pull request still needed? If AppVeyor will support the xUnit 2.0 reports, my 'problem' will be solved. The nUnit reports will not be 100% correct, though.

**Comment by plioi** [comment]
We can close this issue if you'd like.  I can revisit the NUnit output in the next few weeks to make sure it's up to date with the real schema.

**Comment by plioi** [comment]
This fix has been released in 1.0.0.29.  If you encounter further XML issues, please create a new issue.

**Comment by LodewijkSioen** [comment]
Thanks a lot. I've re-added the testresults to my AppVeyor build and they are now displayed properly.
