### ISSUE TITLE
Add FieldsExpression and allow invocation of parameterless Actions/Funcs

### ISSUE THREAD

**Issue by agross** [fixie/fixie#78]
As a fun side project I was toying with the idea to Build up a Fixie convention to emulate Machine.Specifications. Too bad there is no `FieldExpression` available. Is there any workaround? I looked at `Convention.Config`, bit there seems to be no viable member to invoke.

**Comment by plioi** [comment]
My apologies for the late response, and thanks for your interest!

You're right, there's no existing hook to work with fields in the way that Machine.Specifications does, though that framework has been on my radar as it's proven itself to be a useful resource during Fixie's development (whenever NUnit, xUnit, and Machine.Specifications had to do the same thing behind the scenes, I always found Machine.Specification's solution to be the easiest to understand!).

Although a lot of Fixie's early development and feature set was driven by imitating its biggest competitors (NUnit and NUnit's direct offspring), it's not a long-term goal to support emulating the dramatically-different style of test classes you get with Machine.Specifications, NSpec, and the like. All the frameworks I can think of are opinionated in their own ways, and so is Fixie.  I'm not likely to support field discovery and field execution, erring on the side of test classes looking, feeling, and acting like regular POCOs.
