### ISSUE TITLE
Your thoughts on extended / changed listener functionality

### ISSUE THREAD

**Issue by JonasSamuelsson** [fixie/fixie#80]
In my automated test runner I would like to visualize progress in real time which would require a couple of changes that I would like to get your opinions on
1. Extend Listener with a CaseStarting method, using this I could show which test is currently executing.
   - The reason for this is that if a test is taking a long time to complete or is stuck in an infinite loop it would be easy to see where to start debugging.
2. Calls to Listener.CaseFailed/CasePassed should be executed directly when a test case has completed and not in a batch at the end of the ClassRunner.

If you think this is something that would be accepted I'll start working on a PR right away.

**Comment by JonasSamuelsson** [comment]
I have some concerns regarding how to add the new listener method.
Adding it directly to the interface would be a breaking change and I suspect you dont want that.
A better solution could be to create a new interface CaseStartedListener with the new method, try casting the listener instance to that interface and invoke it if the cast is successful.

What do you think?

**Comment by plioi** [comment]
Closing this in favor of #183.  Fixie 2.0 dramatically changed the listener concept, and a recent development by Microsoft increases the utility of this change for our integration with Test Explorer.
