### ISSUE TITLE
Failing tests on machine with German locale

### ISSUE THREAD

**Issue by paulroho** [fixie/fixie#90]
Some tests that check Fixie's output messages and use regexes to cleanup non-deterministic data such as the elapsed time fail on machines with a locale that does not have a dot for the decimal separator.

These tests are affected:

* ConsoleListenerTests
* AssertionLibraryFilteringTests

Reason is that in the regex used, a dot is assumed as decimal separator for the reported time.

**Comment by plioi** [comment]
I've applied a fix that combines your fix with Victor Grigoriu's fix from #100. The combination is both simple and future-proof.  Thanks to you both!

**Comment by paulroho** [comment]
Out of curiosity, why did you not want to include the tests?

**Comment by plioi** [comment]
I find tests-of-test-classes to be a little excessive.  Tests are valuable to the extend they provide confidence to make change and to catch problems.  The tests-of-tests wouldn't catch the sort of culture issues that might remain.

**Comment by paulroho** [comment]
Fair enough, but how can you be sure that the fix works, i.e. that the fixed tests work under one of  the locales in question (since you did not have the problem with your locale)?

**Comment by plioi** [comment]
I tried out both pull requests under different locales, in order to witness the problem and to witness it start to pass.
