### ISSUE TITLE
Discovering static methods as tests

### ISSUE THREAD

**Issue by seemantr** [fixie/fixie#93]
First of all I want to say that Fixie looks amazing. I like the complete flexibility that I get when using Fixie. It has helped me in few difficult situations.

I was wondering if Fixie can be used to detect static public methods as test cases. I have tried few things but nothing seems to be working. In case you find it an odd request I want to give you some context.

I extensively use F# for unit testing. In F# you have modules which can contain methods. These modules get compiled as static classes with the methods as static methods. Obviously this approach works well when testing pure methods.

So for example one could easily write F# tests in Xunit as below:

```
module Maths.``Vector operations``

[<Fact>] 
let ``The addition of real numbers is commutative`` () =
    // Assertions etc
```

Now if Fixie could work with static methods then I could get rid of the above Fact attribute, thus making my tests even more terse.

Fixie works perfectly if I use C# like classes and methods in F#. It's just that I find it a bit more verbose compared to the above.

**Comment by plioi** [comment]
Right now, it has to be an instance method.  This happens here: https://github.com/fixie/fixie/blob/master/src/Fixie/Internal/MethodDiscoverer.cs

I'm not just going to close this issue, though.  There have been similar requests like allowing a convention to include private methods, too.  I'll collect all the similar requests and see if they can be supported without breaking things for more typical usages before deciding on the feature.

**Comment by seemantr** [comment]
@plioi Thanks for the quick response.

**Comment by plioi** [comment]
This is now possible with the 2.0.0-rc-0001 release candidate.

FSharp.Tests.fsproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fixie" Version="2.0.0-rc-0001" />
    <PackageReference Include="Shouldly" Version="2.8.3" />
    <DotNetCliToolReference Include="Fixie.Console" Version="2.0.0-rc-0001" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="CalculatorTests.fs" />
  </ItemGroup>

</Project>
```

(Note that although this is a 'netcoreapp', it could have been the regular framework instead 'net452', and note that there is no fs file with a "Main" entry point method because Fixie provides that for you as if by magic.)

CalculatorTests.fs:

```fs
module FSharp.Tests.CalculatorTests

open Fixie.Integration
open Shouldly

let ShouldAdd() =
    let calculator = new Calculator()
    calculator.Add(2, 3).ShouldBe(5)

let ShouldSubtract() =
    let calculator = new Calculator()
    calculator.Subtract(5, 3).ShouldBe(2)
```
